# Site settings
title: NLP Evaluation - Course web page
subtitle: > # ignore newlines until "description:"
    Course web page, WS 2022 - 2023
    <a href="http://www.sfs.uni-tuebingen.de">SfS</a>,
    <a href="http://uni-tuebingen.de/">University of Tübingen</a>
description: > # ignore newlines until "baseurl:"
    This is the course web page for NLP evaluation course
    taught in the linguistic department (SfS), University of Tübingen.
baseurl: ""
url: "https://iscl-enlp.github.io"
github_username:  iscl-enlp

encoding: utf-8

# Build settings
markdown: kramdown
